### ISSUE TITLE
프로젝트 주제 결정하기

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#1]
산학 프로젝트 주제 선정을 위한 의견 공유

**Comment by shshinc** [comment]
**순 공부 시간 측정 서비스**

> 공부 할 때, 공부 시간을 정확히 측정 하기 어려움

> 공부 시간을 정확히 측정하기 위해 어플이나 타이머를 사용할 경우 공부를 시작할 때, 측정 시작 버튼을 누르는 것을 까먹는 경우 있음. 또한 타이머를 켜 둔 상태에서 딴 짓을 한 경우에도 그 시간 이 공부 시간에 포함됨.

> 노트북의 카메라를 사용하여 사용자가 공부를 하는지 다른 것을 하는지 모니터링 한다. 사용자가 공부를 하는 경우에는 자동으로 시간이 측정되지만 공부를 하지 않고 딴 짓을 할 경우에는 자동으로 시간 측정이 종료되어 최종적으로 하루 동안의 총 공부 시간을 측정해 주는 서비스를 제공

최종적으로 공부를 정말 열심히 해야 하는 학생들이나 취준생에게 도움이 되는 서비스라 예상됨

**Comment by 9incero** [comment]
**이어폰 볼륨 모니터링 서비스**

> 현대인은 많은 시간에 이어폰, 에어팟, 헤드셋등의 기기를 사용함. 하지만 그런 기기들을 오래 사용하거나 볼륨을 크게 높여 사용하면 청각에 손상을 줄 수 있음. 

> 이어폰, 에어팟, 헤드셋등의 기기들을 일주일에 얼마나 사용했는지, 적정사용시간은 벗어나지 않았는지, 알맞은 볼륨으로 듣고 있는지 등을 모니터링함. 적정사용시간이 넘었을 경우 사용자에게 사용시간을 줄이라고 권고함. 또한 사용자가 적정볼륨을 넘겨 사용했을 경우 적정볼륨을 알려주고 그에 맞춰 사용하도록 유도하는 서비스 제공. 

음악을 즐겨듣거나, 소음을 피해 이어폰등을 너무 자주 사용하는 현대인의 청각건강에 도움이 되는 서비스라 예상됨.

**Comment by miseeo** [comment]
**펫 홈캠 서비스**

> 반려동물을 키우는 1인 가구가 많은데, 집을 비운 사이 반려동물이 위험에 빠질 수 있음

> 반려동물이 일정 시간 이상 움직이지 않으면 등록된 휴대폰으로 알림 전송, 주인이 직접 캠으로 확인할 수 있도록 함

혼자 시간을 보내는 반려동물이 걱정되지만 하루종일 캠을 들여다볼 수 없는 상황에 걱정을 덜어주는데 도움이 될 거라 예상됨
