### ISSUE TITLE
동작 인식 라이브러리를 무엇을 쓰는 게 좋을까요?

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#10]
### YOLO와 TensorFlow 중에 어떤 라이브러리를 사용하는 것이 좋을까요?

**YOLO**
- 단일 신경망 구조로 구성이 단순하고 빠름
- 주변 정보까지 학습하며 이미지 전체를 처리하기 때문에 background error가 작음
- 새로운 이미지에 대해서도 정확도가 높음
- SOTA 객체 검출 모델에 비해 정확도가 다소 떨어짐

**TensorFlow Object Detection API**
- 이미지를 인식할 수 있도록 TensorFlow에서 제공하는 라이브러리
- 직접 사용자 데이터를 업로드하여 사용자가 원하는 Object Detection System을 만들 수 있음

**Comment by 9incero** [comment]
저는 YOLO 라이브러리가 좋을 것 같습니다.
저희가 학습시킬 다양한 데이터가 별로 없기때문에 새로운 이미지에 대해서 정확도가 높은 YOLO 라이브러리가 좋을 것 같습니다

**Comment by shshinc** [comment]
제가 직접해보니 YOLO알고리즘을 사용해 보는 것이 더 좋을 것 같았습니다. 직접 커스터마이징 할수가 있어 model의 용량을 줄일 수 있고 저희는 실시간으로 진행해야 하기에 단순하고 빠른 YOLO가 저희 프로젝트에 더 알맞는 라이브러리 일것이라고 생각됩니다.
