### ISSUE TITLE
git에서 문제가 발생했습니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#11]
git에서 바로 branch를 생성하려고 했었으나 계속 실패하는 상황이 발생했었습니다. 이에 대해 해결방안을 알고 계신 분이 계신가요?

**Comment by 9incero** [comment]
혹시 README.md 파일을 수정해보셨나요?

**Comment by shshinc** [comment]
README파일을 생성만 해놓고 딱히 수정은 하지 않았습니다. 수정해보고 branch를 생성하니 branch가 정상적으로 생성되는 것을 알 수 있었습니다. 감사합니다.
