### ISSUE TITLE
YOLO알고리즘 문제

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#12]
YOLO알고리즘을 실행해보는 과정에서 output_layers 변수에서 invalid index to scalar variable. 라는 에러라는 문제가 발생하였습니다. 혹시 해결방법이 있을까요?

**Comment by miseeo** [comment]
제가 찾아보니, opencv 버전에 따라 발생하는 오류 같습니다.

`pip install opencv-python==4.5.1.48`

위 방법으로 opencv 다른 버전을 설치하시면 해결될 것입니다.

**Comment by shshinc** [comment]
버전 문제였군요! 버전을 바꾸었더니 바로 해결되었습니다.
감사합니다!
