### ISSUE TITLE
영상 버퍼링

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#13]
yolo알고리즘을 사용해 사물을 구분하는 중 웹캠 영상이 버퍼링이 계속 걸리는 문제가 발생하였습니다. 이에 대해 해결방안을 물어보고자 합니다.

**Comment by 9incero** [comment]
웹캠영상을 일정시간 단위로 캡쳐하고 캡쳐된 사진을 통해 yolo알고리즘을 사용해 보는 것이 어떨까요? 영상보다 사진이 더 빠르게 분석이 가능할 것 같습니다.

**Comment by shshinc** [comment]
나중에 그 방법을 사용해 보고 더 성능이 좋은 방식을 이용해 보면 좋을 것 같습니다.

**Comment by shshinc** [comment]
model이 너무 커서 버퍼링이 걸릴수 있다는 부분은 생각해 보지 못했던것 같습니다.
저희가 model을 커스터마이징한 것이 아니라 있는 모델을 가져다 쓰기 때문에 굳이 판단하지 않아도 될 물체또한 판별이 되어 용량이 커져 버퍼링이 걸릴 수 있을 것 같습니다.

**Comment by miseeo** [comment]
그렇다면 저희가 구분해야 할 물체만을 판별할 모델을 새로 만들면 버퍼링 문제가 해결될 것 같습니다.

**Comment by shshinc** [comment]
model을 직접 커스터마이징하여 캡처하는 방식으로 결정되었으니 이슈를 닫도록 하겠습니다.
