### ISSUE TITLE
2차 멘토 의견 

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#14]
2차 멘토링 후 각자 정리한 내용을 올려주세요.

**Comment by 9incero** [comment]
>  실시간으로 웹캠 영상을 받아 인식시킬 때 생기는 버퍼링 문제

- 웹캠 영상의 품질을 조절해보는 것을 추천함.
- 병목지점을 찾아 해결해보는 것을 추천함.
- 동기적인 코드인 것 같으니 파이썬의 비동기적인 문법(asyncio 사용)으로 처리하는 것을 추천함.
- 웹캠 영상의 모든 부분을 실시간으로 처리하는 것이 아니라 성능을 보고 합리적인 시간간격으로 잘라 인식시키는 것을 추천함.

**Comment by miseeo** [comment]
>  사용자마다 공부하는 자세가 다른데, 이를 어떻게 판단할지 

-  첫 번째로 모션인식을 통해 사용자마다 다른 공부 행위(턱 괸 자세, 눈동자 위치등)를 파악하고 두 번째로 그 파악한 인식을 학습시켜서 공부를 하는지 안하는지 판단하게 하는 두 단계를 거치는 것이 좋을 것 같다고 생각함.

**Comment by shshinc** [comment]
- 프론트엔드의 시각화도 중요하니 모델링이 완성될 때까지 기다리지 않고 모델과 약속된 결과 형식을 정해서 지금부터 빨리 개발을 진행하는 것을 추천함
