### ISSUE TITLE
클라우드 서버 선택

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#15]
교수님의 추천에 따라 클라우드 서버를 네이버, AWS 중에 하나를 선택하여 진행하려 합니다. 
둘 중 어떤 서버로 하는 것이 좋을까요?

다른 의견이 있으시면 함께 남겨주세요.

**Comment by shshinc** [comment]
django는 어떻게 생각하시나요?? django서버를 만들면 내장되어 있는 database가 있고 파이썬을 기반으로 사용할 수 있어 파이썬에서 사용하는 라이브러리를 사용할 수 있다고 알고 있습니다.

저희는 sql, js보다는 파이썬에 더 익숙하기 때문에 의견을 남겨봅니다.

**Comment by 9incero** [comment]
저도 django가 좋다고 생각합니다.
웹을 만들때 프론트와 관련된 프레임워크를 사용하지 않고 html만을 이용해서 만들 수 있기에 웹 개발에 익숙치 않은 저희에게 좋을 것 같습니다!
