### ISSUE TITLE
모델을 구현시에 트레이닝 이미지 수집

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#16]
모델을 구현할 시 이미 있는 구현되어 있는 알고리즘을 사용해서 하면 pen을 인식하지 못하는 문제가 발생하였습니다. 그렇기에 커스터마이징을 진행해야 할 것 같은데 트레이닝 이미지 수집은 어떠한 방식으로 진행하는 것이 나을까요?

**Comment by shshinc** [comment]
저의 생각은 우선 구글에서의 이미지를 크롤링을 통해 사진을 저장하는 방식을 생각해 보았습니다.  저희가 원하는 사진을 구할 수 있기 때문입니다.

**Comment by miseeo** [comment]
저도 원하는 데이터를 많이 수집할 수 있는 이미지 크롤링이 좋을 것 같습니다.
