### ISSUE TITLE
공부시간 측정에 관련해서 의견을 남겨봅니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#18]
저희가 공부시간을 측정하는데 공부를 하고있을때에 공부시간을 측정하는 것보다는 시작을 하면 공부시간을 계속 측정하다가 공부를 하지 않을 시에 공부시간을 멈추는 방식으로 진행하는 방법으로 생각해 보았습니다.

여러분들은 어떻게 생각하시나요??

**Comment by 9incero** [comment]
저도 그것이 좋을 것 같습니다! 공부를 하지 않는 시간만 보내주는 것이 더욱 효율적일 것 같습니다.

**Comment by miseeo** [comment]
저도 사용자가 원할 때 측정을 시작할 수 있기 때문에 그 방법이 좋다고 생각합니다.
