### ISSUE TITLE
필요한 역할을 정해봅시다

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#2]
### 필요한 역할

**본인이 익숙한 언어와 원하는 역할이 있다면 적어주시기 바랍니다!**

**Comment by shshinc** [comment]
**익숙한 언어**
- [ ] python
- [ ] C++

**그동안 해봤던 프로젝트**

- 자세교정어플 : CNN기법을 이용한 자세 분류 및 아두이노 센서를 이용한 데이터 입출력 담당
- 코로나 사망자수 예측 시스템 : 웹 크롤링을 통해 데이터를 입력받고 이를 예측하는 모델 구축하는 역할

**원하는 역할**

- BackEnd 혹은 Model

**Comment by miseeo** [comment]
**익숙한 언어**
- Python

**원하는 역할**
- Backend

**Comment by 9incero** [comment]
**익숙한 언어**

- js

**그동안 해왔던 프로젝트**

- 자세교정어플: 안드로이드 스튜디오를 사용하여 안드로이드 앱 개발

**원하는 역할**

- frontend
