### ISSUE TITLE
github 커밋에 대한 질문

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#20]
1 commit ahead, 2 commits behind main. 
이라는 문구가 제 브랜치에만 뜨는데 이것을 해결할 방안 아시는분 계신가요?

**Comment by shshinc** [comment]
git clone을 해보셨나요? 저도 그러한 문제가 있었는데 git clone을 해보니 문제가 해결되었습니다.

**Comment by 9incero** [comment]
git clone 후에 브랜치를 생성하니 정상적으로 작동되었습니다! 감사합니다
