### ISSUE TITLE
시간 측정관련하여 의견을 남겨봅니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#21]
2가지 방식중 하나를 선택해야 할것 같아서 이슈를 남겨봅니다.

- 영상을 토대로 시간을 측정하는 방법입니다. 버퍼링이 걸리는 문제가 생겼긴했지만 모델의 용량을 줄여보는 방향으로 진행해보면 해결할 수도 있을것 같습니다.

- 영상의 사진을 캡처하여 사진에 대해 공부하는지 안하는지를 판단하여 시간을 측정하는 방법이 있습니다. 이방법에 대해서는 사진을 몇분단위로 캡처해야 할지를 정해야 할 것 같습니다.

**Comment by shshinc** [comment]
저는 해봐야 겠지만 우선은 영상을 토대로 진행해보고 버퍼링이 너무 심하다면 캡처하는 방식으로 진행해 봐야 할 것 같다고 생각합니다.

**Comment by shshinc** [comment]
아니면 2가지 방식을 모두 진행해보고 더 효과가 좋은 방식으로 진행해 보는 것은 어떨까요?

**Comment by miseeo** [comment]
저는 버퍼링이 아주 심하지만 않다면 영상을 토대로 시간을 측정하는 것이 더 좋을 것 같습니다.
캡처는 캡처 시간 단위를 정하기 힘들어서 영상에 비해 정확한 시간 측정이 어렵기 때문입니다.

**Comment by 9incero** [comment]
저는 캡처하는 방식이 더 좋을 것 같습니다!
영상의 경우 용량이 너무 크고 버퍼링이 심하게 걸릴 것 같기에 
캡처 시간 단위를 짧게 한다면 성능도 나쁘지 않을 것 같아 더 좋을 것 같습니다.
