### ISSUE TITLE
웹 폰트 선택

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#22]
![image](https://user-images.githubusercontent.com/105656886/202695568-fd21f9ba-0ea2-4de7-ab23-b732e6b820a4.png)
웹사이트를 구성하는 폰트를 무엇을 할지 위 사진의 두가지 폰트중에서 고민중에 있습니다!
왼쪽 폰트가 좋을지 오른쪽 폰트가 좋을지 의견 남겨주세요!

**Comment by miseeo** [comment]
전 오른쪽 폰트가 더 부드러워서 보기 좋은 것 같습니다!

**Comment by shshinc** [comment]
저도 오른쪽 폰트가 더 괜찮을것 같습니다!
