### ISSUE TITLE
발명설계서 관련 질문

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#24]
발명의 명칭을 어떻게 하면 좋을까요?
각자 생각하는 주요 키워드를 넣었으면 좋겠습니다.
저는 일단 순수공부시간이 중요한 키워드 같습니다.

**Comment by miseeo** [comment]
저는 시간 자동 측정이 중요한 키워드라고 생각합니다.

**Comment by shshinc** [comment]
발명의 명칭으로는

- 순수공부시간 자동 측정 시스템 및 방법

으로 하는것이 어떤가요?

**Comment by 9incero** [comment]
좋은 것 같습니다!
