### ISSUE TITLE
피어리뷰 관련 질문

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#25]
솔루션 관련 이슈에서 

> 목표시간이 채워지면 어떻게 되는지에 대한 설명이 없는 것 같습니다. 추가적으로 설명을 덧붙여야 할 것 같고, 목표시간을 채우게 되면 자동으로 1부터 다시 시작인지, 만약 어떠한 창이 뜬다면, 사용자가 화면을 보지 못한 상태에 목표시간을 채운 시간이 지나버린다는 가정으로 계속 시간 측정이 되도록 해야 한다고 생각합니다.

라고 코멘트가 왔는데 목표시간이 채워질 경우 어떤 방식으로 반응하는 것이 좋을까요?

**Comment by shshinc** [comment]
목표시간을 다 채웠을 때 목표 공부시간을 다 채웠습니다 라고 팝업창을 띄어주면 괜찮지 않을까요?

**Comment by miseeo** [comment]
목표시간 통계를 보여주는 도넛차트에 목표 시간 달성 이후 초과 공부시간을 좀 더 진한 색으로 표시해 나타내주는 것은 어떨까요?

**Comment by shshinc** [comment]
두가지 방안다 괜찮은 방안이라고 생각합니다.
