### ISSUE TITLE
웹 관련해서 토론해볼만한 것이 있습니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#27]
- 색깔을 나눠 (빨간색-스트레칭 시간, 초록색-딴짓하다 공부에 집중하는 시간, 주황색-순수공부시간) 이런 식으로 성취감과 딴짓을 보완하는 웹을 만드는 의견을 제시합니다.

이렇게 웹을 구성하는 것에 대해서 어떻게 생각하시나요?

**Comment by miseeo** [comment]
스트레칭 시간은 측정하기 어려우니 딴짓하는 시간과 순수 공부시간에 대해서만 해당 의견처럼 진행하면 좋을 것 같습니다.

**Comment by shshinc** [comment]
웹에 해당 의견처럼 진행하는 것으로 알고 이슈 닫도록 하겠습니다.
