### ISSUE TITLE
pull request관련 질문입니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#29]
현재 feature_modeling에 있는 내용을 pull request하려고 하였는데

- Can’t automatically merge. Don’t worry, you can still create the pull request.

위와 같은 오류가 발생합니다. 혹시 해결책을 하시는분 계신가요?

**Comment by 9incero** [comment]
작업 브랜치와 대상 브랜치의 버전이 너무 달라져서 발생하는 것 같습니다. 
대상 브랜치 소스를 작업 브랜치에 머지하고 다시 푸쉬하면 될 것 같습니다.

**Comment by shshinc** [comment]
알려주신 방법으로 해보니 해결되었습니다. 감사합니다.
