### ISSUE TITLE
공부를 하지 않은 상황은 어떻게 판단하면 좋을까요?

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#3]
공부를 하는 중과 공부를 하지 않는 중을 구분을 해야하는데 무엇을 기준으로 구분해야 할까요??

**Comment by shshinc** [comment]
우선 핸드폰이 카메라 내에 존재한다면 이는 공부하지 않은 상황이라고 판단해야 할 것 같습니다.

**Comment by miseeo** [comment]
공부한다면 보통 펜을 사용하니까 펜이 없는 경우도 공부하지 않는다고 판단하면 좋을 것 같습니다.

**Comment by shshinc** [comment]
이 문제에 대해서 계속 생각해 봐야할 문제이기 때문에 이슈를 닫지 않고 계속 열어두겠습니다.

**Comment by 9incero** [comment]
펜이 있어도 펜을 쥐고 있는 손이 화면에 나타나지 않는다면 공부하는 것이 아니기 때문에 손과 펜이 나타나야 공부한다고 판단하면 될 것 같습니다.

**Comment by shshinc** [comment]
기간이 다가왔기에 이슈를 닫도록 하겠습니다.
