### ISSUE TITLE
파이썬 가상환경 오류

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#32]
파이썬 가상환경을 만들고 source ./activate 를 하는 과정에서 

> 'source'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는 배치 파일이 아닙니다.

라는 오류가 뜹니다. 이 경우 어떻게 해야할까요?

**Comment by miseeo** [comment]
git bash를 사용하면 해결될 것입니다!

**Comment by 9incero** [comment]
해결되었습니다. 감사합니다!
