### ISSUE TITLE
모델 관련 질문입니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#33]
지금 코랩으로 모델을 학습시켜 best.pt파일로 만들었습니다. 이 파일을 opencv랑 연동해서 써야하는데 어떻게 해야 할 지를 모르겠습니다.

**Comment by shshinc** [comment]
제가 
model.load_state_dict(torch.load('best.pt'))
model = torch.load('model.weights')
YOLO_net = cv2.dnn.readNet(model)
이렇게 모델을 사용하고 있는데 이부분에서 계속 오류가 발생합니다.

**Comment by 9incero** [comment]
혹시 확장자 바꿔서 해보셨나요? weights 확장자로 바꿔보는 것이 좋을 것 같습니다

**Comment by shshinc** [comment]
확장자를 바꾸었는데도 문제가 발생합니다....

**Comment by shshinc** [comment]
확장자와 cfg파일을 모두 설정하여 사용하였더니 문제가 해결되었습니다. 문제를 해결하였으니 이슈를 닫도록 하겠습니다.
