### ISSUE TITLE
TemplateDoesNotExist 오류

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#34]
프로젝트를 실행하면 TemplateDoesNotExist 오류가 나옵니다.
필요한 템플릿은 다 만들었는데 왜 오류가 나는 걸까요..?

**Comment by shshinc** [comment]
[https://june98.tistory.com/81](https://june98.tistory.com/81)
위 사이트에서 비슷한 내용을 가지고 문제를 해결하였습니다.
참고하시면 좋을 것 같습니다.

**Comment by 9incero** [comment]
만든 html파일이름과 경로를 다시 확인해보는 것이 좋을 것 같습니다

**Comment by miseeo** [comment]
경로 지정을 잘못해서 발생한 오류였네요. 해결했습니다 감사합니다!
