### ISSUE TITLE
git에서 발생하는 이슈

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#35]
git에서 pull를 할 경우

- Pull is not possible because you have unmerged files

이와 같은 오류가 발생합니다. .idea/workspace.xml 파일때문에 그런것 같은데 혹시 해결방안이 있을까요?

**Comment by miseeo** [comment]
git stash --all 명령어를 사용하면 문제가 해결될 것 같습니다.

**Comment by shshinc** [comment]
명령어를 사용하였더니 문제가 해결되었습니다. 감사합니다.
