### ISSUE TITLE
pen 인식 관련 이슈입니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#36]
이미 있는 yolo3.weight파일을 사용하게 되면 pen을 인식못하는 문제가 발생합니다. 이문제를 어떻게 해결하면 좋을지 토론해보고자 이슈를 올려봅니다.

**Comment by shshinc** [comment]
우선 제 의견으로는 구글에 있는 이미지들을 받아와 직접 커스터마이징하는 방법이 좋을 것 같다고 생각합니다.

**Comment by 9incero** [comment]
roboflow에서 쉽게 dataset을 만들수 있는 방법이 존재합니다.

**Comment by shshinc** [comment]
2가지 방법 모두 고려해 보겠습니다.
