### ISSUE TITLE
웹 크롤러 도구 관련 토의

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#37]
웹 크롤러 도구중 selenium과 bs4 중 하나를 선택해서 해보려고 합니다.

어떤 도구를 사용하는 것이 더 좋을지 상의를 해보고 결정해 보려고 합니다.

**Comment by 9incero** [comment]
실제 브라우저를 실행 시켜서 돌아가기 때문에, 웹페이지에 구현된 정적인 페이지뿐만 아니라, 동적인 페이지까지 긁어낼 수 있기때문에  selenium이 더 좋은 것 같습니다.

**Comment by miseeo** [comment]
selenium은 사용자에게 제공되는 눈에 보이는 컨텐츠는 전부 크롤링이 가능하지만 컴퓨터 사양에 따라 느릴 수 있고, 자원을 많이 잡아먹기 때문에 bs4가 더 좋을 것 같습니다.

**Comment by shshinc** [comment]
저희는 자원보다는 최대한 많은 dataset을 만드는 것이 목표이기 때문에 selenium 도구를 사용하는 것이 더 알맞다고 생각합니다.

**Comment by shshinc** [comment]
웹 크롤러 도구가 정해졌기 때문에 이슈 닫도록 하겠습니다.
