### ISSUE TITLE
현재 프로젝트 현황 공유

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#38]
현재 자신이 맡은 분야에 대한 진행사항을 알려주시면 되겠습니다!

**Comment by shshinc** [comment]
우선 현재 저는 데이터를 불러와 데이터 셋을 만들고 모델을 학습시키는 부분까지는 진행을 완료한 상태입니다.

**Comment by 9incero** [comment]
현재 저는 메인화면의 프론트까지 완성하고 로그인 프론트 부분을 만들고 있는 상태입니다.

**Comment by miseeo** [comment]
로그인/회원가입 서버 연동과 회원가입 웹 페이지를 디자인하는 중입니다.
