### ISSUE TITLE
회원가입에 필요한 정보에는 무엇이 있을까요?

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#39]
아이디, 비밀번호 외에 더 필요한 정보가 무엇이 있을까요?

**Comment by shshinc** [comment]
전화번호나 이메일 정보가 필요할 것 같다고 생각합니다.

**Comment by 9incero** [comment]
저희는 공부시간측정을 하는 용도이니 현재 무슨 상황에서 공부하는지(ex. 대입, 취준) 체크하는 항목이 있으면 좋을 것 같습니다.
