### ISSUE TITLE
프로젝트에서 차별성

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#4]
저희 서비스에서는 차별성을 어떻게 두어야 할까요?

**Comment by shshinc** [comment]
기존 어플
> 타이머를 직접 껏다 켰다

저희 서비스
> 사용자가 처음에 켜기만 하면 사용자의 행동을 인식하여 공부하지 않을 때 자동으로 타이머가 멈추도록한다.

**Comment by miseeo** [comment]
기존 어플과의 차이점
> 하루/주간 목표 달성 현황 공지

**Comment by 9incero** [comment]
기존의 공부시간 동기부여를 위해 만들어진 어플, 웹의 경우에는 공부시간을 측정하는 기능과 자신을 모니터링하기 위한 기능이 하나의 어플, 웹에 존재하지 않았음. 하지만 지금 만드는 서비스의 경우에는 공부시간 측정 기능과 자신을 모니터링 하기 위한 기능이 함께 들어가있으며 동시에 체크할 수 있다.
