### ISSUE TITLE
회원가입 테두리 색상 고민

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#41]
> ![image](https://user-images.githubusercontent.com/108726251/205285374-22983572-6342-43e8-9e78-f086379201f5.png)
> 1번

> ![image](https://user-images.githubusercontent.com/108726251/205285400-46a229a6-2d39-4b0d-8aa3-25cb99d9eba3.png)
> 2번

입력칸 테두리 색상에 차이가 있는데 어떤 색이 더 좋을까요?

**Comment by 9incero** [comment]
저는 모두 다 검정색 테두리인 것이 통일성있고 좋을 것 같아 2번이 좋을 것 같습니다!

**Comment by shshinc** [comment]
저도 2번이 더 낫다고 생각합니다.

**Comment by miseeo** [comment]
2번으로 결정하겠습니다!
