### ISSUE TITLE
시간 측정 관련 이슈입니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#42]
시간 측정을 어떠한 방식으로 진행할지 결정을 해봐야 할것 같아서 이슈를 만들어 보았습니다.

1. 시간은 계속 흐르는데 사용자가 딴 짓을 할 경우에 딴 짓한 시간을 따로 계산하여 전체시간에서 빼는 방법
2. 사용자가 공부를 할 때부터 시작 측정하는 방법

어떤 방법이 더 좋을 지 이야기 해보면 좋을 것 같습니다.

**Comment by miseeo** [comment]
저는 전체 시간에서 빼는 법이 더 좋을 것 같습니다

**Comment by 9incero** [comment]
저도 전체시간에서 빼는 방법이 더 좋은 것 같습니다. 전체 순수공부시간양을 일정시간마다 갱신해주면 될 것 같습니다.

**Comment by shshinc** [comment]
그럼 1번의 방식으로 하는 것으로 하고 이슈 닫겠습니다.
