### ISSUE TITLE
영상 캡처시 이슈

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#43]
영상을 캡처하여 시간을 측정해볼 계획인데 몇분 단위로 캡처해봐야 할까요?

**Comment by 9incero** [comment]
30초단위는 어떤가요?

**Comment by miseeo** [comment]
1분 단위로 캡처하는건 어떨까요?

**Comment by shshinc** [comment]
저는 30초가 적당하다고 생각했었습니다. 우선 구현해보고 다시 알려드리겠습니다.

**Comment by shshinc** [comment]
30초로 구현해보니 30초가 괜찮을 듯 하였습니다.
