### ISSUE TITLE
git push 오류

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#44]
git에서 일부 파일을 삭제한후 push를 하려고 하니 

> error: failed to push some refs to

라며 오류가 뜹니다. 혹시 해결방안을 아시나요?

**Comment by miseeo** [comment]
원격저장소에 있는 파일이 로컬 파일에 없을 때 나타나는 오류입니다.
원격저장소에서 로컬로 pull한 후 push하면 해결될 것입니다.
