### ISSUE TITLE
사물인식 라이브러리

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#5]
멘토링 반영사항에서 멘토님께서 사물인식 라이브러리를 2~3개 조사한 후 라이브러리를 선정하라고 하셨습니다. 사물인식 라이브러리에는 무엇이 있을까요?

**Comment by shshinc** [comment]
우선 제가 찾아본 바로는 YOLO알고리즘이 있었습니다.

**Comment by miseeo** [comment]
텐서플로우(Tensorflow) API에서 사물 감지를 지원하는 걸로 알고 있습니다.

**Comment by shshinc** [comment]
YOLOv5모델을 사용해 보니 더 간단하고 직접 커스터마이징 할 수 있다는 큰 장점이 있었습니다. 그렇기에 YOLOv5모델을 사용해 보는것이 좋을 것 같습니다. 이상 이슈 닫겠습니다.
