### ISSUE TITLE
추가적인 정보 제공에 대한 이슈

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#50]
사용자에게 순 공부시간만 제공하는 것 보다는 딴 짓하는 시간까지 포함한 총 시간을 포함해 주는것에 대해 어떻게 생각하시나요?

저는 총 시간까지 알려주는 것이 더 괜찮은 방법이라고 생각합니다. 총 시간대비 공부시간을 알게 되어 자신이 얼마나 열심히 공부를 했는지 정확하게 알게 될 것입니다.

**Comment by 9incero** [comment]
저도 총 시간을 알려주는 것이 더 좋다고 생각합니다.
총 시간과 순 공부시간을 비교하면 더욱 공부 동기부여가 잘 될 것이라고 생각합니다.

**Comment by miseeo** [comment]
저도 총 시간을 알려주는게 사용자에게 사용자가 보기 더 편할것 같습니다.

**Comment by shshinc** [comment]
그럼 총 시간까지 알려주는 것으로 하고 이슈를 닫도록 하겠습니다.
