### ISSUE TITLE
장고 실행시 오류 

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#51]
> TypeError: 'module' object is not iterable

파이썬 가상환경을 통해 장고를 실행하려고 할때 저런 오류메시지가 뜨며 account가 잘못 구성되었다고 이야기합니다.
이 경우 어떻게 해야할까요?

**Comment by miseeo** [comment]
경로 설정이 잘못된 것 같습니다. server urls.py 파일에서 path('account') 줄을 지워주면 될 것입니다.
