### ISSUE TITLE
git pull already up to date 문제

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#53]
로컬에 있는 파일을 수정했는데 원래대로 돌리고 싶어 git pull 명령어를 사용했습니다.
로컬과 원격의 내용이 다른데 Already up to date 라는 메시지가 뜨며 pull이 되지 않습니다.
해결방법 아시는 분 계시면 알려주세요.

**Comment by 9incero** [comment]
> git fetch --all 
git reset --hard origin/<branch명>
git pull origin master

를 해보세요

**Comment by miseeo** [comment]
해결했습니다 감사합니다!
