### ISSUE TITLE
장고 서버 url 문제

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#54]
앱을 만들고 프로젝트의 url를 연결하는 과정에서 어려움을 겪고 있습니다.

> 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('account/',include('account.urls')),
]

이 상황에서 python manage.py runserver 를 하면 화면이 뜨지 않습니다.

**Comment by miseeo** [comment]
접속한 url뒤에 띄우고자 하는 app 명을 입력하시면 됩니다.

> ...8000/<app명>
> ex) ...8000/account
