### ISSUE TITLE
마지막주 프로젝트 진행 현황 공유

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#56]
프로젝트 마무리 시즌인데 다들 자신이 맡은 분야가 어디까지 진행됐는지 알려주세요!

**Comment by miseeo** [comment]
저는 서버랑 회원가입 페이지 연결하고 DB 생성하면 됩니다!

**Comment by 9incero** [comment]
저는 목표시간 post통해 입력받고 통계와 연결하고 로그인 서버와 연동하면 됩니다.

**Comment by shshinc** [comment]
저는 이제 모델과 웹을 연동만 하면 됩니다.
