### ISSUE TITLE
새로운 입력 추가에 대해

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#58]
이전까지는 오늘 공부 목표량만을 사용자에게 입력받았고 주간목표량은 그것을 합산하는 것으로 운영하고자 하였습니다.
하지만 생각해본결과 주간목표량도 사용자에게 입력받는게 어떨까요? 의견 자유롭게 덧붙여주세요!

**Comment by miseeo** [comment]
저도 입력받는게 좋을 것 같습니다!

**Comment by shshinc** [comment]
입력 받는 것이 더 좋을 것 같습니다.
