### ISSUE TITLE
카메라 2개 사용 이슈입니다.

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#59]
저희가 모델을 사용할때 카메라를 사용하고 웹페이지를 실행시킬때도 카메라를 사용합니다. 저희 노트북에 카메라는 1개가 탑재되어있는데 이 부분때문에 오류가 발생할 것 같아 이슈를 적어봅니다...

**Comment by shshinc** [comment]
역시나 문제가 발생하였습니다.
2번의 웹캠을 키는데, 노트북에는 웹캠이 한개가 존재하기에 오류가 발생합니다. 이에 대해 어떻게 해결해야 할까요...?

**Comment by shshinc** [comment]
약간 오해가 있을 수 있을 것 같습니다. 웹캠 2번을 킨다는 뜻은 웹캠을 한번 키고난 다음에 또 웹캠을 키라고 신호가 가는 것 입니다.

**Comment by 9incero** [comment]
두개의 웹캠을 사용하지 않아야 할 것 같습니다.
두개의 웹캠을 사용하지 않으려면 html에서 띄우는 웹캠을 받아 모델링을 적용시켜야할 것 같습니다!

**Comment by shshinc** [comment]
그러면 어떻게 해결할 수 있을까요??

**Comment by 9incero** [comment]
html에서 일정간격으로 캡쳐하고 그 캡쳐한 것을 모델에 보내 적용시키면 될 것 같습니다!

**Comment by shshinc** [comment]
캡쳐한 것을 로컬에 받아 받은 사진으로 모델에 적용시키니 카메라 문제는 해결되었습니다.
