### ISSUE TITLE
중간 발표 자료 준비 논의

### ISSUE THREAD

**Issue by shshinc** [shshinc/study_timer#6]
필요성

Problem 정의

차별성(or Contribution)

해결방법

멘토링 결과에 대한 적용

각자 지정된 부분을 정리해서 올려주세요

**Comment by shshinc** [comment]
차별성으로는 사용자가 켜기만 하면 사용자의 행동을 인식하여 공부하지 않을 때 자동으로 타이머가 멈추도록 한다는 것이다.

**Comment by 9incero** [comment]
해결방법
![시스템구조도](https://user-images.githubusercontent.com/105656886/196992069-940463eb-bd3c-4235-a90e-6f0c5f945bef.png)

**Comment by 9incero** [comment]
> 해결방법 ![시스템구조도](https://user-images.githubusercontent.com/105656886/196992069-940463eb-bd3c-4235-a90e-6f0c5f945bef.png)

수정된 시스템 구조도 업로드합니다!
![image](https://user-images.githubusercontent.com/105656886/197001602-f7a02e63-8068-4231-8561-61c08fe9d83e.png)

**Comment by miseeo** [comment]
필요성
> 공부시간은 학업성취에 영향을 미치는 중요한 변수로, **공부시간의 증가는 학업성취를 향상시킬 수 있는 학습활동임.** 
_(이기종, 곽수란, "학업성취 변화에 영향을 미치는 공부시간 효과 추정", 조사연구(2010.03) 11권 1호 43-61쪽)_ 
따라서 **학업성취도를 늘리고자 하는 사용자에게 도움을 줄 수 있을 것임.**


Problem(Input, Output) 정의
> Input: 사용자의 상반신과 책상이 나오는 웹 캠 영상
Output: 사용자의 총 공부 시간
