### ISSUE TITLE
공부시간 측정 방법에 대한 질문

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#60]
1. 웹사이트에 접속하면 바로 시간 측정 시작
2. 사용자가 측정 시작 버튼을 누르면 시간 측정 시작

둘 중 어떤 방식으로 시간을 측정하는게 좋을까요?
원래 1을 목표로 했었는데 2번이 더 정확한 시간 측정에 도움이 될 것 같아서 여쭤봅니다.

**Comment by 9incero** [comment]
저도 시간 측정 시작을 버튼을 눌러 하는 것이 좋은 것 같습니다.
