### ISSUE TITLE
시간 출력 방식에 대해

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#61]
현재 시간을 출력하는 방식이 모두 다릅니다.
순공시간, 공부시간을 나타내는 방식은 HH:MM:SS이고
목표시간을 설정하는 방식은 형식이 존재하지 않습니다. 
어떻게 통일을 하는 것이 좋을까요?

**Comment by shshinc** [comment]
HH:MM:SS이 방식으로 통일하는 것이 좋을 것 같습니다.

**Comment by miseeo** [comment]
저도 HH:MM:SS 방식이 좋을 것 같습니다.
