### ISSUE TITLE
공부시간 측정 버튼 

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#62]
현재 공부시간을 측정하는 버튼이 이렇게 존재합니다.
![image](https://user-images.githubusercontent.com/105656886/206492349-2d128792-5caf-43f2-86a4-aa17fd955d0f.png)
저희 서비스는 "자동"이 가장 중요한 키워드이기때문에 정지, 재설정을 없애는 것은 어떻게 생각하시나요?

**Comment by shshinc** [comment]
정지, 재설정을 없애는 의견은 좋은 의견이라고 생각합니다.
대신 재설정 버튼을 없애는 대신 일정 시간 주기로 재설정을 해주는 것이 좋을 것 같다고 생각합니다.

**Comment by miseeo** [comment]
저도 없애는게 좋을 것 같습니다

**Comment by 9incero** [comment]
없애는 것으로 하고 이슈 닫겠습니다!
