### ISSUE TITLE
회원가입 비밀번호 보기 옵션 추가

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#63]
회원가입시에 비밀번호를 볼 수 있는 버튼을 추가할까합니다.
클릭하면 비밀번호를 볼 수 있고 다시 클릭하면 비밀번호가 모자이크 되는 방식으로요
어떻게 생각하시나요?

**Comment by shshinc** [comment]
괜찮은 방법이라 생각합니다.

**Comment by 9incero** [comment]
사용자가 원하는 비밀번호를 확인할 수 있는 방법을 주기에 좋을 것 같습니다!

**Comment by miseeo** [comment]
그렇게 하도록 하겠습니다!
