### ISSUE TITLE
시간측정 리셋 주기

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#64]
`재설정 버튼을 없애는 대신 일정 시간 주기로 재설정을 해주는 것이 좋을 것 같다고 생각합니다.`

라고 의견을 주셨습니다.
제 생각에도 재설정 주기를 정하여 새로고침해주는 것이 좋을 것 같습니다.
리셋 주기는 얼마가 적당할까요? 저는 하루정도가 좋다고 생각합니다.

**Comment by shshinc** [comment]
저도 하루단위로 끊어서 해주는게 좋을 것 같습니다.
23:59분에 끊어서 공부시간을 리셋해 주는 것이 더 좋을 것 같다고 생각합니다.

**Comment by miseeo** [comment]
보통 밤샘 공부를 하는 경우가 많으니 저는 새벽 4~5시를 주기로 정하는게 좋을 것 같습니다.
