### ISSUE TITLE
readme 에 쓸 참조, 설치한 라이브러리를 서술해주세요

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#68]
readme에 작성할 참조하거나 설치한 라이브러리를 서술해주세요!
저는 chart.js와 html2canvas의 라이브러리를 사용했습니다.

**Comment by shshinc** [comment]
제가 사용한 부분에 대해서는 readme에 업로드 해놓았습니다.

**Comment by miseeo** [comment]
django-bootstrap4, virtualenv를 사용했습니다
