### ISSUE TITLE
최종 결과물을 어떻게 내는게 좋을까요

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#7]
개인적으로 저는 웹을 사용하는 것이 좋을 것 같습니다.

앱보다는 웹을 사용할때 웹에 출력되는 웹캠화면을 보며 사용자 스스로를 모니터링 효과가 더 클 것 같습니다.
대부분의 노트북은 웹캠이 내장되어있기에 접근성도 나쁘지 않을 것 같습니다.

**Comment by shshinc** [comment]
저 또한 개발기간을 생각해 본다면 웹이 더 괜찮을 것이라고 생각합니다. 나중에 시간이 된다면 앱 또한 제작해 보는 것도 나쁘지 않을 것 같습니다.
