### ISSUE TITLE
js 이벤트에 관한 질문

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#71]
js에서 새로운 html에 들어가자마자 함수를 실행시키고 싶습니다.
새로운 html을 감지하는 이벤트가 있나요? 아니면 새 페이지를 접속했을때 자동으로 함수가 실행되는 방법이 있나요?

**Comment by shshinc** [comment]
window.onload를 사용하면 자동으로 함수가 실행되는 것 같습니다.

**Comment by 9incero** [comment]
해결했습니다! 감사합니다
