### ISSUE TITLE
html끼리 링크 연결

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#72]
로그인, 회원가입 두 html 파일을 서로 링크를 통해 연결하고 싶은데 방법이 있을까요?
```
<a href="login.html"></a>
```
위 코드로는 작동이 안됩니다.

**Comment by 9incero** [comment]
urls.py에서 path()를 통해 설정한 name을 넣어서 <a href="{% url '<name>' %}"></a>로 연결하시면 됩니다.
