### ISSUE TITLE
모델 적용 문제

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#74]
모델을 돌려보니 새로 받아온 사진으로 넘어가지 않고 처음으로 받은 사진만 모델에 중복적으로 적용되는 문제가 발생됩니다.
어떻게 해결하면 좋을까요?

**Comment by shshinc** [comment]
제가 코드를 확인해 보니 count부분이 지역변수로 선언되어 있습니다. 전역변수로 선언하여 함수 내에서 global로 선언 후, 값을 계속 변경해 주면 문제가 해결될 듯 싶습니다.

**Comment by 9incero** [comment]
고치니 해결되었습니다! 감사합니다
