### ISSUE TITLE
토탈 공부시간 출력에 대해

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#77]
저희는 사용자의 강력한 동기부여를 위해 순공시간(딴짓한 시간제외)와 토탈공부시간(딴짓한 시간 포함)을 둘 다 표시하기로 하였습니다.
처음에는 웹페이지에서 따로 구현하려고 했지만 리퀘스트를 보내주기 위해 30초 단위로 캡쳐하고 리퀘스트를 보내줘서 자동 새로고침이 되어 불가능하게 되었습니다. 이것을 어떻게 해결하면 좋을까요?

**Comment by shshinc** [comment]
토탈공부시간을 모델에서 측정하여 웹페이지에 리턴하는 식으로 해결하면 될 것 같습니다.
