### ISSUE TITLE
영상 제작은 어떻게 하는게 좋을까요?

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#78]
기말 발표 때 시연 영상을 찍는게 좋을 것 같은데 어떤식으로 찍는게 좋을까요?
gif, 영상 중에 어떤게 더 보기 편할 것 같나요?

**Comment by shshinc** [comment]
Readme부분에는 공부시간 측정 시작부분까지 과정을 gif파일로 만들어 보여주고, 영상에는 실제로 공부하는 과정까지 담아 내는 것이 좋을 것 같다고 생각합니다.
