### ISSUE TITLE
최종 발표 역할 분담

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#79]
발표 준비 역할을 분담하는게 좋을 것 같은데 어떤 역할이 좋은지 댓글로 남겨주세요!

**Comment by miseeo** [comment]
전 PPT 제작을 맡고싶습니다

**Comment by shshinc** [comment]
항상 해왔던 대로 제가 발표역할을 담당하겠습니다.

**Comment by 9incero** [comment]
저는 결과보고서를 담당하겠습니다.
