### ISSUE TITLE
멘토 의견 정리

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#8]
멘토링 후 멘토님의 의견 정리입니다.
이 의견을 토대로 어떻게 프로젝트를 발전시킬지 남겨주세요.

**요구사항정의서 관련**
요구사항정의서 더욱 자세하게 
요구사항 정의서에 요구사항ID, 요구사항명, 기능 ID, 기능명, 설명, 데이터는 꼭 들어갈 것
요구사항 정의서의 기능적 요구사항을 쓸 때 프론트엔드와 백엔드 부분을 나눠서 쓸 것

**구현 관련**
사물인식 라이브러리는 2-3개정도 조사 후 성능비교를 하고 쓰는 게 좋음
러닝알고리즘을 무엇을 사용할지 고민
공부 시간 통계를 나타낼 때, 시각화가 중요

**기타**
계획서 작성 시 비슷한 비교대상이 되는 서비스를 찾아 차별성을 이야기하기

**Comment by shshinc** [comment]
우선 사물인식 라이브러리를 몇 개 알아보고 사용해 본 후 성능이 가장 좋은 하나의 라이브러리를 정해서 쓰는 것이 더 좋을 것 같습니다.

**Comment by miseeo** [comment]
공부 시간 통계를 나타낼 때 주간 시간 비교는 히스토그램, 목표 달성 현황은 도넛 차트를 사용하면 한눈에 파악하기 좋을 것 같습니다.
