### ISSUE TITLE
post 값 띄우기 오류

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#80]
사용자가 입력한 값을 post로 보내고 받는 과정에서 받은 post를 통계로 띄워주는데 빨간줄이 뜹니다.
빨간줄이 뜸에도 불구하고 실행은 되고 값도 잘 나오는데 이것을 어떻게 해결해야할까요?

**Comment by shshinc** [comment]
빨간줄을 무시하고 진행하면 될 것 같습니다!
