### ISSUE TITLE
로그인, 회원가입 디자인

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#81]
로그인, 회원가입 디자인을 통일하고 싶은데 어떤 디자인으로 하는게 좋을까요?

> <img width="412" alt="image" src="https://user-images.githubusercontent.com/108726251/206838442-46a919c5-adee-4e48-bfea-87b9fcc6ab33.png">

- 현재 회원가입 디자인

> <img width="393" alt="image" src="https://user-images.githubusercontent.com/108726251/206838494-e2606726-d8ae-4e73-b896-c889499e8b9b.png">

- 현재 로그인 디자인

**Comment by 9incero** [comment]
회원가입을 기준으로 통일하는 것이 좋을 것 같습니다.
