### ISSUE TITLE
회원가입/로그인 성공 팝업

### ISSUE THREAD

**Issue by miseeo** [shshinc/study_timer#83]
회원가입/로그인에 성공하면 팝업창으로 알려주어야 할까 고민입니다.
현재는 성공시에 별도의 알림 없이 회원가입은 로그인, 로그인은 메인 화면으로 바로 넘어가도록한 상태입니다.

**Comment by 9incero** [comment]
팝업창을 안띄우고 하는게 더욱 깔끔해보여 좋을 것 같습니다.
