### ISSUE TITLE
캡쳐를 중지하는 버튼에 대해 

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#84]
현재 30초 간격으로 캡쳐하고 시간측정을 자동으로 해주는 과정을 중지하는 버튼이 존재합니다.
하지만 저희의 키워드가 "자동"이기 때문에 없애는 방향으로 가는 것도 나쁘지 않을 것 같습니다.
어떻게 생각하시나요?

**Comment by miseeo** [comment]
저도 자동에 초점을 맞추기 위해 없애는 것이 좋을 것 같습니다.

**Comment by 9incero** [comment]
줄이기로 결정하였습니다! 감사합니다
