### ISSUE TITLE
evaluation에 대해

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#85]
기말발표의 evaluation은 차별성에 대한 평가를 발표해야합니다.
저희의 경우 모델을 차별성으로 제시하였는데 모델의 평가를 어떻게 하면 좋을까요?

**Comment by shshinc** [comment]
저희같은 경우는 정확도 만으로는 모델이 좋은 모델이라고 생각하면 안될 것 같습니다.

예를 들어 모델이 휴대폰이 없는 상황을 잘 인식하지 못하고 있다고 가정해봅시다. 사용자가 공부를 하지 않고 계속 휴대폰을 만지고 있는 상황이라면, 이 모델은 계속 휴대폰을 인식하고 있기에 정확도가 상당히 높을 것입니다. (데이터 셋이 불균형 하기 때문) 
하지만 실제 모델은 휴대폰이 없는 경우에는 잘 인식하지 못하기에 좋은 모델은 아닙니다.

그렇기에 저희는 실제 정답 중에서 모델이 정답이라고 맞춘 수를 의미하는 Recall(재현율)과 모델이 정답이라고 예측한 것 중에서 실제로 정답인 수를 의마하는 Preicision(정밀도)를 이용하여 모델을 평가해야 할 것 같습니다.

그렇기에 Precision(정밀도)와 Recall(재현율)을 가지고 하나의 지표로 나타내기 위해 PR curve를 사용하는 것이 좋을 거 같다고 생각합니다.
