### ISSUE TITLE
요구사항정의서

### ISSUE THREAD

**Issue by 9incero** [shshinc/study_timer#9]
요구사항정의서 작성에 있어 필요한 것들을 남겨주세요!

**Comment by 9incero** [comment]
기능적 요구사항 중 프론트엔드 부분인 웹 사이트 관련 기능

- 사용자 관리 기능
회원가입, 로그인

- 공부시간 측정 기능
하루 공부시간 측정

- 공부목표시간 기능
목표시간 설정, 목표시간 달성 현황

- 공부시간 통계 기능

**Comment by shshinc** [comment]
사용자 데이터 분석 기능

- 어떤 데이터를 입력받고 어떻게 처리할 것인지
- 사물 인식 알고리즘중 YOLO알고리즘과 TensorFlow알고리즘에 대한 설명

**Comment by miseeo** [comment]
주요 기능 설명

1. 공부하는 동작을 인식해 자동으로 정확한 공부 시간 측정 가능
2. 하루/주간 목표 시간 설정 가능
3. 일주일 동안의 공부 시간 비교
4. 공부하는 모습 스스로 모니터링 가능
